site_name: MariaDB Operator
repo_url: https://github.com/mariadb-operator/mariadb-operator
repo_name: mariadb-operator
site_dir: ./site
docs_dir: ./docs
edit_uri: ./edit/main/docs/
remote_branch: gh-pages
theme:
  name: material
  palette: 
    - scheme: default
      primary: "mariadb-blue" 
      accent: "cyan"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: "mariadb-blue" 
      accent: "cyan"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: ./docs/overrides
  logo: assets/mariadb_medium.svg
  favicon: assets/mariadb_favicon.svg
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://r.mariadb.com/join-community-slack
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/mariadb
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mariadb
extra_css:
  - stylesheets/extra.css
exclude_docs: |
  releases/
  Dockerfile
  requirements.txt